default_platform :ios
xcversion(version: '9.0')

platform :ios do
  before_all do
    cocoapods
  end

  desc 'Build App'
  lane :beta do
    ENV['FASTLANE_ITUNES_TRANSPORTER_USE_SHELL_SCRIPT']='1'
    lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING] = {
      'jp.mzp.OctoEye': 'match AppStore jp.mzp.OctoEye',
      'jp.mzp.OctoEye.GithubFileExtension': 'match AppStore jp.mzp.OctoEye.GithubFileExtension'
    }

    match(type: 'appstore')
    gym
    pilot(username: 'mzpppp+apple@gmail.com')
  end

  desc 'Prepare for next build'
  lane :next do
    ensure_git_status_clean
    build_number = increment_build_number
    commit_version_bump
    add_git_tag(tag: "builds/#{build_number}")
  end

  desc 'Runs all the tests'
  lane :test do
    swiftlint(executable: './Pods/SwiftLint/swiftlint')

    scan(
      workspace: 'OctoEye.xcworkspace',
      scheme: 'OctoEye'
    )
  end

  desc 'Prepare for screenshots'
  lane :screenshots do
    snapshot
    frameit(path: './screenshots/', white: true)
  end

  desc 'Prepare for review'
  lane :gm do
    deliver(username: 'mzpppp+apple@gmail.com',
            skip_app_version_update: false,
            screenshots_path: './screenshots',
            skip_binary_upload: true,
            skip_metadata: true,
            overwrite_screenshots: true)
  end
end
