default_platform :ios

platform :ios do
  before_all do
    cocoapods
  end

  desc 'Runs all the tests'
  lane :test do
    swiftlint(executable: './Pods/SwiftLint/swiftlint')
    scan(
      workspace: 'OctoEye.xcworkspace',
      scheme: 'OctoEye'
    )
  end
end
