# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  'iPhone 7',
  'iPhone 7 Plus',
  'iPhone SE',
  'iPad Pro (12.9-inch)',
  'iPad Pro (9.7-inch)'
])

languages([
  'en-US'
])

scheme 'Snapshot'

output_directory './screenshots'

workspace './OctoEye.xcworkspace'

# Arguments to pass to the app on launch. See https://github.com/fastlane/fastlane/tree/master/snapshot#launch-arguments
# launch_arguments(["-favColor red"])
